# Generated by Django 4.1.1 on 2022-09-13 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoGalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('profile_img_url', models.CharField(max_length=1000)),
                ('created_on', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image_url_one', models.CharField(default=None, max_length=1000)),
                ('image_url_two', models.CharField(default=None, max_length=1000)),
                ('image_url_three', models.CharField(default=None, max_length=1000)),
                ('country', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=90)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('content', models.CharField(max_length=25000)),
                ('categories', models.ManyToManyField(related_name='categories', to='gogalapi.category')),
                ('tags', models.ManyToManyField(related_name='tags', to='gogalapi.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogalapi.gogaluser')),
            ],
        ),
        migrations.CreateModel(
            name='MyGoGal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_gal_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendee', to='gogalapi.gogaluser')),
                ('go_gal_picker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friender', to='gogalapi.gogaluser')),
            ],
        ),
    ]
